### ISSUE TITLE
Modloader dll and ONI QoL mk2

### ISSUE THREAD

**Issue by eleroy5** [javisar/ONI-Modloader#46]
## Prerequisites

- [x] I've made sure the game files are ok before installing injector/mods. 
- [x] I am running the latest version (master Branch in GitHub)
- [x] I've checked the logs to see if I can find the problematic mod (test the mods one by one if needed)
- [x] I checked the documentation and forums and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Environment

- OS: 
- ONI Version: 
- ONI-Modloader Version: 

## Output log

Check for error logs in:

- `\OxygenNotIncluded\Mods\Mod_Log.txt`
- `\OxygenNotIncluded\Mods\_Logs`
- Windows: `%USERPROFILE%\AppData\LocalLow\Klei\Oxygen Not Included\output_log.txt`
- Linux: `$home/.config/unity3d/Klei/Oxygen Not Included/Player.log`
- MacOS: `$home/Library/Logs/Unity/Player.log`

## Relevant Code

```Csharp
// TODO(you): code here
```

**Comment by eleroy5** [comment]
After the release of ONI QoL mk2 on steam I wanted play a new game. To be sure to have a proper install i have uninstall ONI and erase the remaining folder. I have reinstall the game, load the last master branch of ONI Modloader.dll in the managed folder and ONI common in the mods folder.
I have install one mod for bigger zoom for test.
The game run but with no mod activated. And the log file is not generated.
I have check all i can think and test other mods but the game runs without any mods and no log generated for modloader/mods.
Is the last dll working with QoL mk2? As i have check many times the install instructions I must say I am lost this time. An idea?
I love so much ONI. But most of mods are so good at playing with i can hardly accept to play without them.
Thanks for your help.
I am running with w10 64b. No problem playing ONI with mods before the QoL mk2 update.
And No log generated to help find what is the problem. very frustrating!!

**Comment by javisar** [comment]
Look for output_log.txt file or equivalent.

http://support.kleientertainment.com/customer/portal/articles/2744766-logs-and-useful-information-for-bug-reports

**Comment by eleroy5** [comment]
Found it
[output_log.pdf](https://github.com/javisar/ONI-Modloader/files/2895999/output_log.pdf)

If i don't mistake it's due to mono.cecil.dll
But i check and the file is the last update and I have put it in Managed and Mods and ONI-Common.

**Comment by javisar** [comment]
Not sure what is the problem but your Mods folder seems to be a bit messed up.
Mono.cecil.dll file appears to be corrupted and duplicated in various places. Also some other mods are duplicated I think.
I'd advice to start all over again. Try to download again the mods. Make sure you ONLY put Modloader.dll into Managed folder, no other mod files.
Then put BiggerCameraZoomOut from into Mods folder and try to start the game and check if it works. If I recall correctly, the zoom out only works after you load a game (not with a new game)
If you use any mods that requires ONI-Common, be sure to put the whole ONI-Common folder into Mods folder (mono.cedil will be inside) and nothing more.

**Comment by Truinto** [comment]
Hey, I had the same issue after updating Modloader.dll. Turns out I didn't download the dll file, but intead the html code for the site. Idk why, but there is no download button anywhere, so I usually right click and "save as", but you need to do that on the lowest level, or you download the website disguised as dll file.
Easy check, open the file in notepad. If it has text, you got the wrong file.

**Comment by javisar** [comment]
If it helps, in order to download the latest version, there is a green button "Clone or Download" at the top right of the root git url:
https://github.com/javisar/ONI-Modloader
https://github.com/javisar/ONI-Modloader-Mods
Then press "Download Zip"

Also, there are zip files for mod loader and mods
https://github.com/javisar/ONI-Modloader/releases
https://github.com/javisar/ONI-Modloader-Mods/releases

**Comment by eleroy5** [comment]
Thanks. I retry and this time it works. Don't know why but the mono.cecil.dll is not the same. Others dll are the same.  And this time it works.
Can't wait to play. It's a couple of day i don't.
Many thanks again.
