### ISSUE TITLE
Object/Tile Status Window is not opening

### ISSUE THREAD

**Issue by FenrirZeroZero** [javisar/ONI-Modloader#5]
If i try to load my save i can't see the status window when i click on stuff. (savegame attached)

If i remove the modloader the menu shows just fine. (The menu that shows on the right site where you can set prios, deconstrukt see current temp etc)

The problem dosn't show on a new game unless i load a new game after i load the affected save.

[output_log.txt](https://github.com/javisar/ONI-Modloader/files/1907226/output_log.txt)
[Save.zip](https://github.com/javisar/ONI-Modloader/files/1907229/Save.zip)

**Comment by Midnight-Steam** [comment]
Mods used:
AlternateOrdersMod
CameraControllerMod
CustomWorldMod
DraggablePanelMod
FastModeMod
ImprovedGasColourMod
PressureDoorMod
SensorsMod
SpeedControlMod
StorageLockerMod
MaterialColor
=======================
I'm going to take a guess and say it's either the AlternateOrdersMod or DraggablePanelMod

**Comment by FenrirZeroZero** [comment]
AlternateOrdersMod 

It seems to be that. 
And thanks i didn't now you could remove mods from the pack ^^"

**Comment by javisar** [comment]
It may be solved now. Test it please. I close this issue. Open a new one in
https://github.com/javisar/ONI-Modloader-Mods
